# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastPDist <- function(Ar, Br) {
    .Call('_CelliD_fastPDist', PACKAGE = 'CelliD', Ar, Br)
}

MCAStep1 <- function(X) {
    .Call('_CelliD_MCAStep1', PACKAGE = 'CelliD', X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call('_CelliD_MCAStep2', PACKAGE = 'CelliD', Z, V, Dc)
}

